/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjlinguagemvisual;

/**
 *
 * @author ezequ
 */
public class FrameIndex extends javax.swing.JFrame {

    /**
     * Creates new form FrameIndex
     */
    public FrameIndex() {
        initComponents();
        IFrameMenu menu = new IFrameMenu(desktopPaneFrame);
        desktopPaneFrame.add(menu);
       
        menu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneFrame = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFilme = new javax.swing.JMenu();
        mnIInserir = new javax.swing.JMenuItem();
        mnBuscarF = new javax.swing.JMenuItem();
        mnSessao = new javax.swing.JMenu();
        mnInserirS = new javax.swing.JMenuItem();
        mnBuscarS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout desktopPaneFrameLayout = new javax.swing.GroupLayout(desktopPaneFrame);
        desktopPaneFrame.setLayout(desktopPaneFrameLayout);
        desktopPaneFrameLayout.setHorizontalGroup(
            desktopPaneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        desktopPaneFrameLayout.setVerticalGroup(
            desktopPaneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        mnFilme.setText("Filme");

        mnIInserir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnIInserir.setText("Novo");
        mnIInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIInserirActionPerformed(evt);
            }
        });
        mnFilme.add(mnIInserir);

        mnBuscarF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnBuscarF.setText("Buscar");
        mnBuscarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarFActionPerformed(evt);
            }
        });
        mnFilme.add(mnBuscarF);

        jMenuBar1.add(mnFilme);

        mnSessao.setText("Sessao");

        mnInserirS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnInserirS.setText("Nova");
        mnInserirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInserirSActionPerformed(evt);
            }
        });
        mnSessao.add(mnInserirS);

        mnBuscarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mnBuscarS.setText("Buscar");
        mnBuscarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarSActionPerformed(evt);
            }
        });
        mnSessao.add(mnBuscarS);

        jMenuBar1.add(mnSessao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneFrame)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnIInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIInserirActionPerformed
        // TODO add your handling code here:
        IFrameInserirFilme inserirSessao = new IFrameInserirFilme(desktopPaneFrame);
        desktopPaneFrame.removeAll();
        desktopPaneFrame.add(inserirSessao);
        inserirSessao.setVisible(true);
        
    }//GEN-LAST:event_mnIInserirActionPerformed

    private void mnBuscarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarFActionPerformed
        // TODO add your handling code here:
        IFrameBuscarFilme buscarFilme = new IFrameBuscarFilme(desktopPaneFrame);
        desktopPaneFrame.removeAll();
        desktopPaneFrame.add(buscarFilme);
        buscarFilme.setVisible(true);
    }//GEN-LAST:event_mnBuscarFActionPerformed

    private void mnBuscarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarSActionPerformed
        // TODO add your handling code here:
        IFrameBuscarSessao buscarSessao = new IFrameBuscarSessao(desktopPaneFrame);
        desktopPaneFrame.removeAll();
        desktopPaneFrame.add(buscarSessao);
        buscarSessao.setVisible(true);
    }//GEN-LAST:event_mnBuscarSActionPerformed

    private void mnInserirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInserirSActionPerformed
        // TODO add your handling code here:
        IFrameInserirSessao inserirSessao = new IFrameInserirSessao(desktopPaneFrame);
        desktopPaneFrame.removeAll();
        desktopPaneFrame.add(inserirSessao);
        inserirSessao.setVisible(true);
    }//GEN-LAST:event_mnInserirSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPaneFrame;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnBuscarF;
    private javax.swing.JMenuItem mnBuscarS;
    private javax.swing.JMenu mnFilme;
    private javax.swing.JMenuItem mnIInserir;
    private javax.swing.JMenuItem mnInserirS;
    private javax.swing.JMenu mnSessao;
    // End of variables declaration//GEN-END:variables
}
