/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjlinguagemvisual;

import bean.Filme;
import dao.FilmeDAO;
import java.awt.Container;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezequ
 */
public class IFrameBuscarFilme extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrameBuscarFilme
     */
    javax.swing.JDesktopPane pane;
    private int linha = 0; 
    private int len =0;
   public IFrameBuscarFilme(javax.swing.JDesktopPane pane) {
        initComponents();
        this.pane = pane;
        
        this.setFrameIcon(null);
        BasicInternalFrameUI f = (BasicInternalFrameUI) this.getUI();
        Container north = (Container) f.getNorthPane();
        north.remove (0);
        
        carregarAtributosTabela();
        len = tbFilmes.getRowCount();
        
    }
    public void carregarAtributosTabela(){
        DefaultTableModel val = (DefaultTableModel) tbFilmes.getModel();
        try {
            FilmeDAO filmes = new FilmeDAO();
            filmes.showFilmes().stream().forEach((Filme f)->{
                val.addRow(new Object[]{
                    f.getId(),
                    f.getNomeFilme(),
                    f.getAnoLancamento(),
                    f.getCategoria().getNomeCategoria(),
                    f.getDireitor().getNomeDiretor()
                    
                });
                
                
            });
        } catch (SQLException ex) {
            System.err.println("erro cod: "+ex);
        }
    }
    public void limparAtrinbutosTabela(){
        ((DefaultTableModel) tbFilmes.getModel()).setRowCount(0);
    }
    public void pesquisa(){
        limparAtrinbutosTabela();
        DefaultTableModel val = (DefaultTableModel) tbFilmes.getModel();

        
        try {
            FilmeDAO filmes = new FilmeDAO();
            filmes.showFilmesBusca(txtPesquisa.getText()).stream().forEach((Filme f)->{
               val.addRow(new Object[]{
                    f.getId(),
                    f.getNomeFilme(),
                    f.getAnoLancamento(),
                    f.getCategoria().getNomeCategoria(),
                    f.getDireitor().getNomeDiretor()
                    
                });
                
                
            });
            if (tbFilmes.getRowCount()==0) {
                
                JOptionPane.showMessageDialog(null, "Não existe Filme com esse Titulo");
                carregarAtributosTabela();
                txtPesquisa.setText(null);
            }
            
        } catch (SQLException ex) {
            System.err.println("erro cod: "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        Filmes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFilmes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPrimario = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnVai = new javax.swing.JButton();

        setEnabled(false);
        setOpaque(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        Filmes.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        Filmes.setText("Filmes");

        tbFilmes.setAutoCreateRowSorter(true);
        tbFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Lancameto", "Categoria", "Diretor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbFilmes);
        if (tbFilmes.getColumnModel().getColumnCount() > 0) {
            tbFilmes.getColumnModel().getColumn(0).setMaxWidth(50);
            tbFilmes.getColumnModel().getColumn(2).setMaxWidth(70);
            tbFilmes.getColumnModel().getColumn(3).setMaxWidth(94);
        }

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setText("Procurar:");

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyTyped(evt);
            }
        });

        btnPrimario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnPrimario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primeiro.png"))); // NOI18N
        btnPrimario.setText("Primeiro");
        btnPrimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimarioActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proximo.png"))); // NOI18N
        btnProximo.setText("Proximo");
        btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N
        btnUltimo.setText("Ultimo");
        btnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnVai.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnVai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        btnVai.setText("Vai");
        btnVai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(114, 114, 114)
                        .addComponent(Filmes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVai))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAtualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrimario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Filmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProximo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrimario)
                        .addComponent(btnAnterior)
                        .addComponent(btnUltimo)))
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here: 
        IFrameMenu menu = new IFrameMenu(this.pane);
        this.pane.add(menu);
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        // TODO add your handling code here:74
        System.out.println("prjlinguagemvisual.IFrameBuscarFilme.btnVaiActionPerformed()");
        pesquisa();
        if (tbFilmes.getRowCount()>0) {
            len = tbFilmes.getRowCount();
        }
        
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        int i = txtPesquisa.getText().length();
       
        if(i>0){
            pesquisa();
            
        }
        else{
            limparAtrinbutosTabela();
            carregarAtributosTabela();
           
        }
        if (len<tbFilmes.getRowCount()) {
            int temp = tbFilmes.getRowCount();
            JOptionPane.showMessageDialog(rootPane,"Atualizado com sucesso!\n"+Integer.toString(temp)+""
                    + " novo (s) iten(s)");
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso!\nNem um novo registro encontado.");
        }
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPrimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimarioActionPerformed
        // TODO add your handling code here:
        linha=0;
        tbFilmes.setRowSelectionInterval(linha,linha);
        
    }//GEN-LAST:event_btnPrimarioActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        linha = tbFilmes.getRowCount()-1;
        tbFilmes.setRowSelectionInterval(linha,linha);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        if (linha== tbFilmes.getRowCount()-1) {
            linha = 0;
            tbFilmes.setRowSelectionInterval(linha, linha);
        }
        else{
            linha++;
            tbFilmes.setRowSelectionInterval(linha, linha);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (linha <= 0) {
            linha = tbFilmes.getRowCount()-1;
            tbFilmes.setRowSelectionInterval(linha, linha);
        }
        else{
            
            linha--;
            tbFilmes.setRowSelectionInterval(linha, linha);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnVaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaiActionPerformed
        // TODO add your handling code here:
        pesquisa();
        
        if (tbFilmes.getRowCount()>0) {
            len = tbFilmes.getRowCount();
        }
    }//GEN-LAST:event_btnVaiActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyCode()== evt.VK_CLEAR) {
            if (txtPesquisa.getText().length()==0) {
                carregarAtributosTabela();
            }
        }
    }//GEN-LAST:event_txtPesquisaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filmes;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPrimario;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVai;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFilmes;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
