/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjlinguagemvisual;

import java.awt.Container;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ezequ
 */
public class IFrameMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrameMenu
     */
    javax.swing.JDesktopPane pane;
    public IFrameMenu(javax.swing.JDesktopPane pane) {
        initComponents();
        this.pane = pane;
    
        this.setFrameIcon(null);
        BasicInternalFrameUI f = (BasicInternalFrameUI) this.getUI();
        Container north = (Container) f.getNorthPane();
        north.remove (0); 
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInserirFilme = new javax.swing.JButton();
        btnBuscarFilme = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnInserirSessao = new javax.swing.JButton();
        btnBuscarSessao = new javax.swing.JButton();

        setEnabled(false);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(616, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lado_Easy-Resize.com.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Cinema");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        jLabel2.setText(" COLLECTION");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lado_Easy-Resize.com.jpg"))); // NOI18N

        btnInserirFilme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnInserirFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inserirFilme.png"))); // NOI18N
        btnInserirFilme.setText("Inserir Filme");
        btnInserirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFilmeActionPerformed(evt);
            }
        });

        btnBuscarFilme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarFilmes.png"))); // NOI18N
        btnBuscarFilme.setText("Buscar Filme");
        btnBuscarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFilmeActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo640.jpg"))); // NOI18N

        btnInserirSessao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnInserirSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/InserirSessao.png"))); // NOI18N
        btnInserirSessao.setText("Inserir Sessão");
        btnInserirSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirSessaoActionPerformed(evt);
            }
        });

        btnBuscarSessao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BuscarSessao.png"))); // NOI18N
        btnBuscarSessao.setText("Buscar Sessão");
        btnBuscarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSessaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarFilme)
                    .addComponent(btnInserirFilme))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirSessao)
                    .addComponent(btnBuscarSessao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirFilme)
                    .addComponent(btnInserirSessao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFilme)
                    .addComponent(btnBuscarSessao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFilmeActionPerformed
        // TODO add your handling code here:
        IFrameBuscarFilme buscarFilmes = new IFrameBuscarFilme(pane);
        this.pane.add(buscarFilmes);
        buscarFilmes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarFilmeActionPerformed

    private void btnInserirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFilmeActionPerformed
        // TODO add your handling code here:
        IFrameInserirFilme inserirFilme = new IFrameInserirFilme(pane);
        this.pane.add(inserirFilme);
        inserirFilme.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInserirFilmeActionPerformed

    private void btnInserirSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirSessaoActionPerformed
        // TODO add your handling code here:
        IFrameInserirSessao inserirSessao = new IFrameInserirSessao(pane);
        this.pane.add(inserirSessao);
        inserirSessao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInserirSessaoActionPerformed

    private void btnBuscarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSessaoActionPerformed
        // TODO add your handling code here:
        IFrameBuscarSessao buscarSessao = new IFrameBuscarSessao(pane);
        this.pane.add(buscarSessao);
        buscarSessao.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBuscarSessaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFilme;
    private javax.swing.JButton btnBuscarSessao;
    private javax.swing.JButton btnInserirFilme;
    private javax.swing.JButton btnInserirSessao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
